sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t zubairmoosa/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true zubairmoosa/docker-react npm run test
