sudo: required
language: generic
services: 
  - docker

before_install: 
  - docker build -t zubairmoosa/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true zubairmoosa/docker-react npm run test

deploy: 
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "Dockerreact-env-1"
 bucket_name: "elasticbeanstalk-us-east-2-849343488395"
 bucket_path: "docker-react"
 on: 
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY