# Specify base image
FROM node:alpine
WORKDIR /app

# Install some dependencies
COPY ./package.json ./

RUN npm config set registry http://registry.npmjs.org/
RUN npm set strict-ssl false
RUN npm install --legacy-peer-deps

COPY ./ ./

# Set start command
CMD [ "npm", "run", "start" ]